application: lastfm-friend-rank
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

inbound_services:
- xmpp_message

handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: main.py
